name: Greybus Module CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: greybus

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: greybus
        toolchains: arm-zephyr-eabi

    - name: Build for beagleconnect_freedom
      run: |
        west build -b beagleconnect_freedom -p always greybus/samples/subsys/greybus/net -- -DEXTRA_CONF_FILE=overlay-802154-subg.conf

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cc1352-firmware
        path: |
          build/zephyr/zephyr.bin
        compression-level: 0
