name: Greybus Module CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "zephyrprojectrtos/ci:latest"
    
    env:
      ZEPHYR_BASE: ${{ github.workspace }}/zephyr
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
      ZEPHYR_SDK_INSTALL_DIR: /opt/sdk/zephyr-sdk
      WS: ${{ github.workspace }}
      GB: ${{ github.workspace }}/greybus
      PATH: ${{ github.workspace }}/zephyr/scripts:${{ github.workspace }}/tools/net-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        path: greybus

    - name: Setup Environment
      run: |
        west init -l greybus
        west update
        cd ${ZEPHYR_BASE}
        ${WS}/tools/net-tools/loop-socat.sh &

    - name: Build for beagleconnect_freedom
      run: |
        cd ${ZEPHYR_BASE}
        west build -b beagleconnect_freedom -p always ${GB}/samples/subsys/greybus/net -- -DEXTRA_CONF_FILE=overlay-802154-subg.conf
