name: Greybus Module CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "zephyrprojectrtos/ci:latest"
    
    env:
      ZEPHYR_BASE: ${{ github.workspace }}/zephyr
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains
      WS: ${{ github.workspace }}
      GB: ${{ github.workspace }}/greybus
      # Ensure Python venv is in PATH (from the Dockerfile)
      PATH: /opt/python/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        path: greybus

    - name: Debug Workspace Structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Workspace: ${{ github.workspace }}"
        echo "Contents of current directory:"
        ls -la
        echo "Contents of workspace:"
        ls -la ${{ github.workspace }} || echo "Workspace directory doesn't exist"
        mkdir -p ${{ github.workspace }}
        echo "Created workspace directory"

    - name: Initialize West Workspace
      run: |
        cd ${{ github.workspace }}
        pwd
        ls -la
        west init -l greybus
        west update

    - name: Build for beagleconnect_freedom
      run: |
        cd ${ZEPHYR_BASE}
        west build -b beagleconnect_freedom -p always ${GB}/samples/subsys/greybus/net -- -DEXTRA_CONF_FILE=overlay-802154-subg.conf
