name: Greybus Module CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "zephyrprojectrtos/ci:latest"
    
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains:${{ github.workspace }}/zephyr/share/zephyr-package/cmake
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains
      ZEPHYR_BASE: ${{ github.workspace }}/zephyr
      WS: ${{ github.workspace }}
      GB: ${{ github.workspace }}/greybus
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        path: greybus

    - name: Initialize West Workspace
      run: |
        west init -l greybus
        west update

    - name: Build for beagleconnect_freedom
      run: |
        west build -b beagleconnect_freedom -p always greybus/samples/subsys/greybus/net -- -DEXTRA_CONF_FILE=overlay-802154-subg.conf
