name: Greybus Module CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "zephyrprojectrtos/ci:latest"
    
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        path: greybus

    - name: Initialize West Workspace
      run: |
        west init -l greybus
        west update

    - name: Build for beagleconnect_freedom
      run: |
        export ZEPHYR_BASE=$(pwd)/zephyr
        export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:$ZEPHYR_BASE/share/zephyr-package/cmake"
        
        west build -b beagleconnect_freedom -p always greybus/samples/subsys/greybus/net -- -DEXTRA_CONF_FILE=overlay-802154-subg.conf
